---
apiVersion: v1
kind: Service
metadata:
  name: myspringapp
spec:
  selector: 
    app: myspringapp
  type: LoadBalancer  
  ports:
  - name: docauto
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: myspringapp
metadata:
  name: myspringapp
spec:
  selector:
    matchLabels:
      app: myspringapp
  replicas: 1
  
  template:
    metadata:
      labels:
        app: myspringapp
    spec:          
      
      containers:
      - name: myspringapp
        image: 578110936779.dkr.ecr.eu-west-2.amazonaws.com/google-jib:9371acc
        imagePullPolicy: Always
        
        resources:
          requests:
            cpu: 1
            memory: 512Mi
          limits:
            cpu: 2
            memory: 2Gi
