node:
  name: nodejs
  namespace: node
  imagetag: 1.7.0
  resources:
    limits:
      cpu: 100m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 200Mi
#
service:
  name: node-service
  type: ClusterIP
