node:
  name: nodejs
  namespace: wsd
  imagetag: 1.1.1
  resources:
    limits:
      cpu: 100m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 200Mi
#
service:
  name: node-service
  type: ClusterIP
