apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.name }}
  namespace: {{ .Values.redis.namespace }}
spec:
  selector: 
    app: {{ .Values.redis.name }}
  ports:
  - name: {{ .Values.redis.name }}
    protocol: TCP
    port: 6379
    targetPort: 6379
  # - name: exporter
  #   protocol: TCP
  #   port: 9121
  #   targetPort: 9121
