---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.node.namespace }}
spec:
  selector:
    app: {{ .Values.node.name }}
  type: {{ .Values.service.type }}
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
