node:
  name: nodejs
  namespace: wsd
  imagetag: 3.0.0-SNAPSHOT
  resources:
    limits:
      cpu: 100m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 200Mi
#
service:
  name: node-service
  type: ClusterIP
#
ingress:
  ingressClass: alb
