node:
  name: nodejs
  namespace: wsd
  imagetag: $IMAGE_TAG-SNAPSHOT
  resources:
    limits:
      cpu: 100m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 200Mi
#
service:
  name: node-service
  type: ClusterIP
