{{- $appname := .Values.deployment.name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $appname }}
  namespace: {{ .Values.deployment.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ $appname }}
  replicas: {{ .Values.deployment.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ $appname }}
    spec:
      containers:
      - name: {{ $appname }}
        image: {{ .Values.deployment.image }}
        imagePullPolicy: Always
        resources:
          requests:
            cpu: {{ .Values.deployment.resources.requests.cpu | quote }}
            memory: {{ .Values.deployment.resources.requests.memory | quote }}
          limits:
            cpu: {{ .Values.deployment.resources.limits.cpu | quote }}
            memory: {{ .Values.deployment.resources.limits.memory | quote }}
        env:
        {{- toYaml .Values.deployment.env | nindent 8 }}
        ports:
        - containerPort: {{ .Values.deployment.port }}
        volumeMounts:
        - name: 
          mountPath: 
      volumes:
      - name: 
        persistentVolumeClaim:
          claimName: 