apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.deployment.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.deployment.port }}
      targetPort: http
      protocol: TCP
      name: {{ .Values.deployment.port }}-tcp
  selector:
    app: {{ .Values.deployment.name }}
